### ISSUE TITLE
not working: return {}

### ISSUE THREAD

**Issue by emanuellandell** [Anarchid/blender2lus#6]
I have tried to get it to work with multiple files, but the result is always the same, no animations.

example) https://www.turbosquid.com/FullPreview/Index.cfm/ID/1012108

get's exported as:

```
return {
}
```

**Comment by Anarchid** [comment]
What blender version are you using? This probably needs an update for Blender 2.8

**Comment by Anarchid** [comment]
Also, your file seems to be using an armature-based animation; SpringRTS doesn't support that yet in any way, so the addon doesn't either.

If you've figured out a way to make Spring support skeletal animations with IK, i'll be happy to patch up the addon to work with that!
